---
- name: Lokales Debian Setup
  hosts: local
  become: true

  tasks:
    - name: APT Cache aktualisieren
      apt:
        update_cache: yes

    - name: Programme installieren
      apt:
        name:
          - xorg
          - i3
          - rofi
          - git
          - alacritty
          - chromium
          - feh
          - i3blocks
          - fzf
          - gcc
          - ripgrep
          - unzip
          - xclip
        state: latest
