---
- name: setting up the system
  hosts: local
  become: true

  tasks:
    - name: updating apt
      apt:
        update_cache: yes

    - name: installing requirements
      apt:
        name:
          - git
          - curl
          - fzf
          - gcc
          - ripgrep
          - unzip
          - xclip
          - make
        state: latest

    - name: installing desktop tools
      apt:
        name:
          - xorg
          - i3
          - i3blocks
          - picom
          - feh
          - rofi
          - alacritty
          - chromium

    - name: installing prgramming tools
      apt:
        name:
          - npm
          - luarocks
          - python3-venv
